openapi: 3.0.4
info:
  title: Monster Hunter API
  description: Microservicio para el consumo de servicios de Monster Hunter API
  version: 1.0.0
  contact:
    name: TU NOMBRE
    email: tuemail@mail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
externalDocs:
  description: Monster Hunter World Database API
  url: https://docs.mhw-db.com/
servers:
  - url: http://localhost:3000/ms-monsterhunter-neg
    description: Local
tags:
  - name: health
    description: Operaciones relacionadas al estado del servicio
  - name: monstruos
    description: Operaciones relacionadas a monstruos
paths:
  /health:
    get:
      summary: Retorna el estado del servicio
      description: Retorna el estado del servicio
      operationId: getHealth
      tags:
        - health
      responses:
        '200':
          description: Servicio activo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  /monstruos:
    get:
      summary: Obtiene todos los monstruos
      description: Retorna una lista con todos los monstruos
      operationId: getAllMonstruos
      tags:
        - monstruos
      externalDocs:
        description: Monster Hunter World Database - Monsters Endpoint
        url: https://docs.mhw-db.com/#monsters
      responses:
        '200':
          description: Retorno exitoso de los monstruos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Monstruo'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /monstruos/{id}:
    get:
      summary: Obtiene un monstruo en especifico
      description: Retorna un monstruo en especifico basado en su id
      operationId: getMonstruoById
      tags:
        - monstruos
      externalDocs:
        description: Monster Hunter World Database - Monster by ID
        url: https://docs.mhw-db.com/#get-a-specific-monster
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
          required: true
          description: Id del monstruo
          example: 1
      responses:
        '200':
          description: Retorno exitoso del monstruo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monstruo'
        '400':
          description: Parametros invalidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParametersError'
        '404':
          description: Monstruo no encontrado
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
components:
  schemas:
    Monstruo:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Aptonoth
        descripcion:
          type: string
          example: Docile herbivores that g… will flee immediately
        tipo:
          type: string
          example: small
        especie:
          type: string
          example: herbivore
        elementos:
          type: array
          items:
            type: string
            example: earth
        ubicaciones:
          type: array
          items:
            $ref: '#/components/schemas/Ubicacion'
        resistencias:
          type: array
          items:
            $ref: '#/components/schemas/Resistencia'
        dolencias:
          type: array
          items:
            $ref: '#/components/schemas/Dolencia'
        debilidades:
          type: array
          items:
            $ref: '#/components/schemas/Debilidad'
        recompensas:
          type: array
          items:
            $ref: '#/components/schemas/Recompensa'
    Ubicacion:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Ancient Forest
        recuentoZona:
          type: integer
          example: 17
    Resistencia:
      type: object
      properties:
        elemento:
          type: string
          example: thunder
        condicion:
          type: string
          example: ''
    Dolencia:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Paralysis
        descripcion:
          type: string
          example: Paralysis renders the hu…alyzed if they are hit
        recuperacion:
          $ref: '#/components/schemas/Recuperacion'
        proteccion:
          $ref: '#/components/schemas/Proteccion'
    Debilidad:
      type: object
      properties:
        elemento:
          type: string
          example: water
        estrellas:
          type: integer
          example: 3
        condicion:
          type: string
          example: ''
    Recompensa:
      type: object
      properties:
        id:
          type: integer
          example: 1
        item:
          $ref: '#/components/schemas/Item'
    Recuperacion:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Proteccion:
      type: object
      properties:
        habilidades:
          type: array
          items:
            $ref: '#/components/schemas/Habilidad'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Lightcrystal
        descripcion:
          type: string
          example: A precious and extremely…sed for crafting tools
        valor:
          type: integer
          example: 1150
        rareza:
          type: integer
          example: 5
        limite:
          type: integer
          example: 99
    Habilidad:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Paralysis Resistance
        descripcion:
          type: string
          example: Reduces the duration of paralysis
    Validation:
      type: object
      properties:
        campo:
          type: string
          example: id
        mensaje:
          type: string
          example: Id debe ser numerico
    Dependency:
      type: object
      properties:
        name:
          type: string
          example: Monster Hunter API
        status:
          type: string
          example: UP
        responseTime:
          type: integer
          example: 120
        url:
          type: string
          example: https://api.mhw-db.com
    Health:
      type: object
      properties:
        status:
          type: string
          example: UP
        timestamp:
          type: string
          format: date-time
          example: '2023-10-10T10:00:00.000Z'
        version:
          type: string
          example: '1.0.0'
        uptime:
          type: integer
          example: 3600000
        dependencies:
          type: array
          items:
            $ref: '#/components/schemas/Dependency'
    ParametersError:
      type: object
      properties:
        detalles:
          type: array
          items:
            $ref: '#/components/schemas/Validation'
    BusinessError:
        type: object
        properties:
            codigo:
                type: string
                example: 'MH001'
            mensaje:
                type: string
                example: Error de negocio
    ServerError:
        type: object
        properties:
            codigo:
                type: string
                example: '500'
            mensaje:
                type: string
                example: Ha ocurrido un error interno